Repository laminas-api-tools/api-tools-oauth2, pull requests merged in 2021-06, with the labels that each got.

#32 Switch to GHA CI Workflow
  .github/workflows/continuous-integration.yml
  .gitignore
  .laminas-ci.json
  .travis.yml
  bin/bcrypt.php
  composer.json
  composer.lock
  config/module.config.php
  phpcs.xml
  phpcs.xml.dist
  src/Adapter/BcryptTrait.php
  src/Adapter/Exception/RuntimeException.php
  src/Adapter/MongoAdapter.php
  src/Adapter/PdoAdapter.php
  src/Controller/AuthController.php
  src/Controller/Exception/ExceptionInterface.php
  src/Controller/Exception/RuntimeException.php
  src/ExceptionInterface.php
  src/Factory/AuthControllerFactory.php
  src/Factory/MongoAdapterFactory.php
  src/Factory/OAuth2ServerFactory.php
  src/Factory/OAuth2ServerInstanceFactory.php
  src/Factory/PdoAdapterFactory.php
  src/Module.php
  src/Provider/UserId/AuthenticationService.php
  src/Provider/UserId/AuthenticationServiceFactory.php
  src/Provider/UserId/UserIdProviderInterface.php
  test/Adapter/Pdo/AccessTokenTest.php
  test/Adapter/Pdo/AuthorizationCodeTest.php
  test/Adapter/Pdo/BaseTest.php
  test/Adapter/Pdo/ClientTest.php
  test/Adapter/Pdo/JwtAccessTokenTest.php
  test/Adapter/Pdo/JwtBearerTest.php
  test/Adapter/Pdo/PublicKeyTest.php
  test/Adapter/Pdo/RefreshTokenTest.php
  test/Adapter/Pdo/ScopeTest.php
  test/Adapter/Pdo/UserCredentialsTest.php
  test/Controller/AuthControllerTest.php
  test/Controller/AuthControllerWithCustomAdapterTest.php
  test/Controller/AuthControllerWithLaminasAuthenticationServiceTest.php
  test/Controller/AuthControllerWithMongoAdapterTest.php
  test/Controller/CustomAdapter.php
  test/Controller/TestAsset/BodyParams.php
  test/Controller/TestAsset/CustomProblemDetailsException.php
  test/Factory/AuthControllerFactoryTest.php
  test/Factory/MongoAdapterFactoryTest.php
  test/Factory/OAuth2ServerFactoryTest.php
  test/Factory/PdoAdapterFactoryTest.php
  test/TestAsset/autoload/mongo/global.php
  test/TestAsset/autoload/pdo/global.php
  test/TestAsset/autoload_custom/global.php
  test/TestAsset/autoload_laminas_authenticationservice/global.php
  test/TestAsset/autoload_mongo/global.php
  test/TestAsset/custom.application.config.php
  test/TestAsset/laminas.authenticationservice.application.config.php
  test/TestAsset/mongo.application.config.php
  test/TestAsset/pdo.application.config.php
Labels: Enhancement

#29 PHP 8.0 support
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Controller/AuthController.php
  test/Adapter/Pdo/AbstractBaseTest.php
  test/Adapter/Pdo/AccessTokenTest.php
  test/Adapter/Pdo/AuthorizationCodeTest.php
  test/Adapter/Pdo/ClientCredentialsTest.php
  test/Adapter/Pdo/ClientTest.php
  test/Adapter/Pdo/JwtAccessTokenTest.php
  test/Adapter/Pdo/JwtBearerTest.php
  test/Adapter/Pdo/PublicKeyTest.php
  test/Adapter/Pdo/RefreshTokenTest.php
  test/Adapter/Pdo/ScopeTest.php
  test/Adapter/Pdo/UserCredentialsTest.php
  test/Controller/AuthControllerTest.php
  test/Controller/AuthControllerWithCustomAdapterTest.php
  test/Controller/AuthControllerWithLaminasAuthenticationServiceTest.php
  test/Controller/AuthControllerWithMongoAdapterTest.php
  test/Controller/TestAsset/CustomProblemDetailsException.php
  test/Factory/AuthControllerFactoryTest.php
  test/Factory/MongoAdapterFactoryTest.php
  test/Factory/OAuth2ServerFactoryTest.php
  test/Factory/PdoAdapterFactoryTest.php
Labels: Enhancement

#26 Qa/psalm
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml.dist
  src/Adapter/MongoAdapter.php
  src/Adapter/PdoAdapter.php
  src/Controller/AuthController.php
  test/Adapter/Pdo/AccessTokenTest.php
  test/Adapter/Pdo/AuthorizationCodeTest.php
  test/Adapter/Pdo/ClientCredentialsTest.php
  test/Adapter/Pdo/ClientTest.php
  test/Adapter/Pdo/JwtAccessTokenTest.php
  test/Adapter/Pdo/JwtBearerTest.php
  test/Adapter/Pdo/PublicKeyTest.php
  test/Adapter/Pdo/RefreshTokenTest.php
  test/Adapter/Pdo/ScopeTest.php
  test/Adapter/Pdo/UserCredentialsTest.php
  test/Controller/AuthControllerTest.php
  test/Controller/AuthControllerWithCustomAdapterTest.php
  test/Controller/AuthControllerWithLaminasAuthenticationServiceTest.php
  test/Controller/AuthControllerWithMongoAdapterTest.php
  test/Controller/TestAsset/CustomProblemDetailsException.php
  test/Factory/AuthControllerFactoryTest.php
  test/Factory/MongoAdapterFactoryTest.php
  test/Factory/OAuth2ServerFactoryTest.php
  test/Factory/PdoAdapterFactoryTest.php
Labels: Enhancement, hacktoberfest-accepted

#34 Ensure webmozart/assert is present as a package requirement
  composer.json
  composer.lock
Labels: Bug

#37 Fix BC break in BcryptTrait
  src/Adapter/BcryptTrait.php
  src/Adapter/MongoAdapter.php
  src/Adapter/PdoAdapter.php
Labels: BC Break, Bug
